---
title: "Study 1: Analysis"
author: "Emily Pohl"
format: docx
editor: visual
---

```{r}
library(haven)
library(dplyr)
library(psych)
library(ggplot2)
library(parameters)
library(interactions)
library(dplyr)
library(psych)
library(ltm) 
library(rstatix) 
library(car) 
library(ggplot2)
library(haven)
library(tidyr)
library(broom)
library(apaTables)
library(effectsize) 
library(lavaan)
library(semTools)
library(modsem)
```

data_buric : N = 1141
data_clean : N = 426 = Many Teachers

```{r}
data_buric <- read_sav("teachers_longitudinal.corr.sav")


data_all <- read_sav("00 ManyTeachers2026.03.06.sav")
n0 <- nrow(data_all)
data_clean <- data_all

n0 <- nrow(data_clean)

data_clean <- data_clean %>%
  filter(!(AT_fail_sum %in% c(2, 3)) | is.na(AT_fail_sum))
n1 <- nrow(data_clean)
cat("After AT_fail_sum filter:", n1, "rows (dropped", n0 - n1, ")\n")

data_clean <- data_clean %>%
  filter(!(clean_schooltype %in% c(1, 2, 3, 4)))
n2 <- nrow(data_clean)
cat("After clean_schooltype filter:", n2, "rows (dropped", n1 - n2, ")\n")

data_clean <- data_clean %>%
  filter(currentwork != 4 | is.na(currentwork))
n3 <- nrow(data_clean)
cat("After currentwork filter:", n3, "rows (dropped", n2 - n3, ")\n")

data_clean <- data_clean %>%
  filter(LANGUAGE != "nan" | is.na(LANGUAGE))
n4 <- nrow(data_clean)
cat("After LANGUAGE filter:", n4, "rows (dropped", n3 - n4, ")\n") 

nrow(data_all)
nrow(data_clean)
```

# Teachers Buric

```{r}
describe(data_buric$T3EXP)
```


```{r}
data_buric$EmEx_3 <- rowMeans(data_buric[, paste0("EmEx", 1:6, "_3")], na.rm = TRUE)
data_buric$Joy_3 <- rowMeans(data_buric[, paste0("Joy", 1:4, "_3")], na.rm = TRUE)
data_buric$Anx_3 <- rowMeans(data_buric[, paste0("Anx", 1:4, "_3")],na.rm = TRUE)
data_buric$Ang_3 <- rowMeans(data_buric[, paste0("Ang", 1:4,"_3")], na.rm = TRUE)

data_buric$EmEx_4 <- rowMeans(data_buric[, paste0("EmEx", 1:6, "_4")], na.rm = TRUE)
data_buric$Joy_4 <- rowMeans(data_buric[, paste0("Joy", 1:4, "_4")], na.rm = TRUE)
data_buric$Anx_4 <- rowMeans(data_buric[, paste0("Anx", 1:4, "_4")], na.rm = TRUE)
data_buric$Ang_4 <- rowMeans(data_buric[, paste0("Ang", 1:4, "_4")], na.rm = TRUE)

data_buric$NegAff_4 <- rowMeans(
  data_buric[, c(paste0("Anx", 1:4, "_4"),
                 paste0("Ang", 1:4, "_4"))],
  na.rm = TRUE
)

data_buric$NegAff_4 <- rowMeans(
  data_buric[, c(paste0("Anx", 1:4, "_4"),
                 paste0("Ang", 1:4, "_4"))],
  na.rm = TRUE
)

data_buric$NegAff_3 <- rowMeans(
  data_buric[, c(paste0("Anx", 1:4, "_3"),
                 paste0("Ang", 1:4, "_3"))],
  na.rm = TRUE
)
```

```{r}
Rel_NegAff_4 <- data_buric %>% 
  dplyr::select(c(paste0("Anx", 1:4, "_4"),
                  paste0("Ang", 1:4, "_4")))

psych::alpha(Rel_NegAff_4)
```

```{r}
Items_NegAff_4 <- data_buric %>% 
  dplyr::select(c(paste0("Anx", 1:4, "_4"),
                  paste0("Ang", 1:4, "_4")))

cor_matrix <- cor(Items_NegAff_4, use = "pairwise.complete.obs")

cor_matrix
```


```{r}
items_EmEx_3 <- c("EmEx1_3","EmEx2_3","EmEx3_3",
                  "EmEx4_3","EmEx5_3","EmEx6_3")

Rel_EmEx_3 <- data_buric[, items_EmEx_3]


psych::alpha(Rel_EmEx_3)
```


```{r}
Rel_EmEx_3 <- data_buric %>% dplyr::select(paste0("EmEx", 1:6, "_3"))
psych::alpha(Rel_EmEx_3)
```

```{r}
Rel_EmEx_4 <- data_buric %>% dplyr::select(paste0("EmEx", 1:6, "_4"))
psych::alpha(Rel_EmEx_4)
```


Anger: 
t3: .808
t4: .847
```{r}
Rel_Ang_3 <- data_buric %>% dplyr::select(paste0("Ang", 1:4, "_3"))
psych::alpha(Rel_Ang_3)
```

```{r}
Rel_Ang_4 <- data_buric %>% dplyr::select(paste0("Ang", 1:4, "_4"))
psych::alpha(Rel_Ang_4)
```


Anxiety: 
t3: .849
t4: .847
```{r}
Rel_Anx_3 <- data_buric %>% dplyr::select(paste0("Anx", 1:4, "_3"))
psych::alpha(Rel_Anx_3)
```

```{r}
Rel_Ang_4 <- data_buric %>% dplyr::select(paste0("Ang", 1:4, "_4"))
psych::alpha(Rel_Ang_4)
```



Joy: 
t3: .878
t4: .873
```{r}
Rel_Joy_3 <- data_buric %>% dplyr::select(paste0("Joy", 1:4, "_3"))
psych::alpha(Rel_Joy_3)
```

```{r}
Rel_Joy_4 <- data_buric %>% dplyr::select(paste0("Joy", 1:4, "_4"))
psych::alpha(Rel_Joy_4)
```

```{r}
cor.data_buric <- data_buric %>% dplyr::select("EmEx_3", "Ang_3", 
                                       "Anx_3", "Joy_3") 
cor(cor.data_buric) 
cor(cor.data_buric,use = "pairwise.complete.obs") 
sum(complete.cases(cor.data_buric))
apa.cor.table(cor.data_buric, landscape = F, filename = "Correlations_Buric_26.03.23.rtf")
```

```{r}
cor.data_buric <- data_buric %>% dplyr::select("EmEx_4", "Ang_4", 
                                       "Anx_4", "Joy_4") 
cor(cor.data_buric) 
cor(cor.data_buric,use = "pairwise.complete.obs") 


apa.cor.table(cor.data_buric, landscape = F, filename = "Correlations_Buric.rtf")
```

```{r}
cor.data_clean <- data_clean %>% dplyr::select("EmEx", "Anger", 
                                       "Anxiety", "Joy") 
cor(cor.data_clean) 
cor(cor.data_clean,use = "pairwise.complete.obs") 


apa.cor.table(cor.data_clean, landscape = F, filename = "Correlations_MT.rtf")
```

## z-Standardization

```{r}
data_buric$EmEx_3_z <- as.numeric(scale(data_buric$EmEx_3))
data_buric$Joy_3_z  <- as.numeric(scale(data_buric$Joy_3))
data_buric$Anx_3_z  <- as.numeric(scale(data_buric$Anx_3))
data_buric$Ang_3_z  <- as.numeric(scale(data_buric$Ang_3))

data_buric$EmEx_4_z <- as.numeric(scale(data_buric$EmEx_4))
data_buric$Joy_4_z  <- as.numeric(scale(data_buric$Joy_4))
data_buric$Anx_4_z  <- as.numeric(scale(data_buric$Anx_4))
data_buric$Ang_4_z  <- as.numeric(scale(data_buric$Ang_4))
```


```{r}
data_buric$gender_factor <- factor(data_buric$T3GENDER,
                                   levels = c(1, 2),
                                   labels = c("male", "female"))
table(data_buric$T3GENDER)
describe(data_buric$T3EXP)
```

```{r}
nobs(model_buric_t3)
nobs(model_buric_t4)
```

## MLR t3 

```{r}
model_buric_t3 <- lm(EmEx_3_z ~ Ang_3_z + Anx_3_z + Joy_3_z + 
                 gender_factor + T3EXP,
               data = data_buric)
summary(model_buric_t3)

confint(model_buric_t3, level = 0.95)  
round(confint(model_buric_t3, level = 0.95), 3)

effectsize(model_buric_t3)

```

## MLR t4
```{r}
nobs(model_buric_t3)
nobs(model_buric_t4)
```

```{r}
model_buric_t4 <- lm(EmEx_4_z ~ Ang_4_z + Anx_4_z + Joy_4_z + 
                 gender_factor + T4EXP,
               data = data_buric)
summary(model_buric_t4)

confint(model_buric_t4, level = 0.95)  
round(confint(model_buric_t4, level = 0.95), 3)

effectsize(model_buric_t4)
```

## Autoregressive Model 

```{r}
model_buric_auto <- lm(EmEx_4_z ~ EmEx_3_z + Ang_3_z + Anx_3_z + Joy_3_z + 
                 gender_factor + T3EXP,
               data = data_buric)
summary(model_buric_auto)

confint(model_buric_auto, level = 0.95)  
round(confint(model_buric_auto, level = 0.95), 3)
```

```{r}
model_buric_long <- lm(EmEx_4_z ~ Ang_3_z + Anx_3_z + Joy_3_z + 
                 gender_factor + T3EXP,
               data = data_buric)
summary(model_buric_long)

confint(model_buric_long, level = 0.95)  
round(confint(model_buric_long, level = 0.95), 3)
```


### SEM 
```{r}
library(semTools)
library(lavaan)

model_buric_t4_sem <- "
MI_EmEx =~ EmEx1_4 + EmEx2_4 + EmEx3_4 + EmEx4_4 + EmEx6_4
MI_Anger =~ Ang1_4 + Ang2_4 + Ang3_4 + Ang4_4
MI_Anxiety =~ Anx1_4 + Anx2_4 + Anx3_4 + Anx4_4
MI_Joy =~ Joy1_4 + Joy2_4 + Joy3_4 + Joy4_4

MI_EmEx ~ MI_Anger + MI_Anxiety + MI_Joy + T3GENDER + T3EXP

"

fit_buric_t4 <- sem(model_buric_t4_sem, data = data_buric)
summary(fit_buric_t4, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)

lavInspect(fit_buric_t4, "nobs")
```

```{r}
library(semTools)
library(lavaan)

model_buric_t4_sem <- "
MI_EmEx =~ EmEx1_4 + EmEx2_4 + EmEx3_4 + EmEx4_4 + EmEx6_4
MI_Anger =~ Ang1_4 + Ang2_4 + Ang3_4 + Ang4_4
MI_Anxiety =~ Anx1_4 + Anx2_4 + Anx3_4+ Anx4_4
MI_Joy =~ Joy1_4 + Joy2_4 + Joy3_4 + Joy4_4

MI_EmEx ~ MI_Anger + MI_Anxiety + MI_Joy + T3GENDER + T3EXP

"

fit_buric_t4 <- sem(model_buric_t4_sem, data = data_buric)
summary(fit_buric_t4, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)

```


```{r}
parameterEstimates(fit_buric_t4, standardized = TRUE, ci = TRUE)
```


```{r}
fit_buric_t4 <- sem(
  model_buric_t4_sem,
  data = data_buric,
  se = "bootstrap",
  bootstrap = 500
)

standardizedSolution(fit_buric_t4, ci = TRUE)
```

```{r}
model_joy_ang <- "
MI_EmEx =~ EmEx1_4 + EmEx2_4 + EmEx3_4 + EmEx4_4 + EmEx6_4
MI_Anger =~ Ang1_4 + Ang2_4 + Ang3_4 + Ang4_4
MI_Joy =~ Joy1_4 + Joy2_4 + Joy3_4 + Joy4_4

MI_EmEx ~ MI_Anger + MI_Joy + T3GENDER + T3EXP

"

fit_model_joy_ang <- sem(model_joy_ang , data = data_buric)
summary(fit_model_joy_ang, standardized = TRUE)
summary(fit_model_joy_ang, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)

```

```{r}
model_joy_anx <- "
MI_EmEx =~ EmEx1_4 + EmEx2_4 + EmEx3_4 + EmEx4_4 + EmEx6_4
MI_Anxiety =~ Anx1_4 + Anx2_4 + Anx3_4 + Anx4_4
MI_Joy =~ Joy1_4 + Joy2_4 + Joy3_4 + Joy4_4

MI_EmEx ~ MI_Anxiety + MI_Joy + T3GENDER + T3EXP

"

fit_model_joy_anx <- sem(model_joy_anx , data = data_buric)
summary(fit_model_joy_anx, standardized = TRUE)
summary(fit_model_joy_anx, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)

```

```{r}
model_joy_negaff <- "
MI_EmEx =~ EmEx1_4 + EmEx2_4 + EmEx3_4 + EmEx4_4 + EmEx6_4
MI_NegAff =~ Ang1_4 + Ang2_4 + Ang3_4 + Ang4_4 + Anx1_4 + Anx2_4 + Anx3_4 + Anx4_4 
MI_Joy =~ Joy1_4 + Joy2_4 + Joy3_4 + Joy4_4

MI_EmEx ~ MI_NegAff + MI_Joy + T3GENDER + T3EXP

"

fit_model_joy_negaff <- sem(model_joy_negaff , data = data_buric)
summary(fit_model_joy_negaff, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)

```


```{r}
fit_model_joy_negaff <- sem(
  model_joy_negaff,
  data = data_buric,
  se = "bootstrap",
  bootstrap = 500
)

standardizedSolution(fit_model_joy_negaff, ci = TRUE)
```


```{r}
model_emex4 <- "
MI_EmEx =~ EmEx1_4 + EmEx2_4 + EmEx3_4 + EmEx4_4 + EmEx6_4

"

fit_emex4 <- sem(model_emex4, data = data_buric)
summary(fit_emex4) 

summary(fit_emex4, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)

```


```{r}
summary(fit_buric_t4, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)
```

```{r}
measurement_model <- '
MI_EmEx =~ EmEx1_4 + EmEx2_4 + EmEx3_4 + EmEx4_4 + EmEx5_4 + EmEx6_4
MI_Anger =~ Ang1_4 + Ang2_4 + Ang3_4 + Ang4_4
MI_Anxiety =~ Anx1_4 + Anx2_4 + Anx3_4 + Anx4_4
MI_Joy =~ Joy1_4 + Joy2_4 + Joy3_4 + Joy4_4
'

fit_cfa <- cfa(measurement_model, data = data_buric, estimator = "MLR")
summary(fit_cfa, fit.measures = TRUE, standardized = TRUE)
```

## CFAs Buric

```{r}
library(lavaan)

# 1 Factor CFA => Negative Affect

model_1factor_NegAff_4 <- '
  NegAff =~ Anx1_4 + Anx2_4 + Anx3_4 + Anx4_4 +
            Ang1_4 + Ang2_4 + Ang3_4 + Ang4_4
'

fit_1factor_NegAff_4 <- cfa(
  model_1factor_NegAff_4,
  data = data_buric,
  estimator = "MLR",
  missing = "fiml"
)

summary(fit_1factor_NegAff_4, fit.measures = TRUE, standardized = TRUE)
```

```{r}
# 2 Factor CFA => Anger and Anxiety

model_2factor_NegAff_4 <- '
  Anx =~ Anx1_4 + Anx2_4 + Anx3_4 + Anx4_4
  Ang =~ Ang1_4 + Ang2_4 + Ang3_4 + Ang4_4
'

fit_2factor_NegAff_4 <- cfa(
  model_2factor_NegAff_4,
  data = data_buric,
  estimator = "MLR",
  missing = "fiml"
)

summary(fit_2factor_NegAff_4, fit.measures = TRUE, standardized = TRUE)
```

```{r}

model_3factor_TES <- '
  Anx =~ Anx1_4 + Anx2_4 + Anx3_4 + Anx4_4
  Ang =~ Ang1_4 + Ang2_4 + Ang3_4 + Ang4_4
  Joy =~ Joy1_4 + Joy2_4 + Joy3_4 + Joy4_4
'

fit_3factor_TES <- cfa(
  model_3factor_TES,
  data = data_buric,
  estimator = "MLR",
  missing = "fiml"
)

summary(fit_3factor_TES, fit.measures = TRUE, standardized = TRUE)
```

```{r}

model_2factor_TES <- '
  Neg =~ Anx1_4 + Anx2_4 + Anx3_4 + Anx4_4 + Ang1_4 + Ang2_4 + Ang3_4 + Ang4_4
  Joy =~ Joy1_4 + Joy2_4 + Joy3_4 + Joy4_4
'

fit_2factor_TES <- cfa(
  model_2factor_TES,
  data = data_buric,
  estimator = "MLR",
  missing = "fiml"
)

summary(fit_2factor_TES, fit.measures = TRUE, standardized = TRUE)
```

```{r}

model_1factor_TES <- '
  TES =~ Anx1_4 + Anx2_4 + Anx3_4 + Anx4_4 + Ang1_4 + Ang2_4 + Ang3_4 + Ang4_4 + Joy1_4 + Joy2_4 + Joy3_4 + Joy4_4
'

fit_1factor_TES <- cfa(
  model_1factor_TES,
  data = data_buric,
  estimator = "MLR",
  missing = "fiml"
)

summary(fit_1factor_TES, fit.measures = TRUE, standardized = TRUE)
```

```{r}
NegAff_items_4 <- data_buric %>%
  dplyr::select(
    all_of(c(paste0("Anx", 1:4, "_4"),
             paste0("Ang", 1:4, "_4")))
  ) %>%
  na.omit()

View(NegAff_items_4)
```

```{r}
TES_items_4 <- data_buric %>%
  dplyr::select(
    all_of(c(paste0("Anx", 1:4, "_4"),
             paste0("Ang", 1:4, "_4"),
             paste0("Joy", 1:4, "_4")))
  ) %>%
  na.omit()

View(TES_items_4)
```

```{r}
library(EFAtools)
N_FACTORS(
  NegAff_items_4,
  criteria = c("SMT", "HULL", "PARALLEL", "EKC", "CD"),
  N_samples = 1000,
  eigen_type_other = c("SMC"),
  gof = "CAF",
  method = "PAF"
)
```

```{r}
library(EFAtools)
N_FACTORS(
  TES_items_4,
  criteria = c("SMT", "HULL", "PARALLEL", "EKC", "CD"),
  N_samples = 1000,
  eigen_type_other = c("SMC"),
  gof = "CAF",
  method = "PAF"
)
```

```{r}
efa <- psych::fa(NegAff_items_4, nfactors = 2, fm = "ml", oblique.scores = TRUE) 
fa.sort(efa)
```


